nfq_weather:
   provider: delegating
   providers:
       openweathermap:
           api_key: '8b14eb2c5beed13dd28c80dffdf74d42'
       delegating:
           providers:
               - yahoo
               - openweathermap
